# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Blogger\BlogBundle\Entity\Usuario: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
        user_provider:
            entity:
                class: Blogger\BlogBundle\Entity\Usuario
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            provider: user_provider
            logout:
                path: /logout
                target: /login
            switch_user: ~
            logout_on_user_change: true

            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/blog/new, roles: ROLE_USER}

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
