#app:
#   resource: '@AppBundle/Controller/'
#  type: annotation
app:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

calcularedad:
    path:     /calculaedad/{anios}
    defaults: { _controller: AppBundle:calculateAge:age }
