#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
app:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

saludo:
    path:     /saludo
    defaults: { _controller: AppBundle:Saludo:saludo }

saludopersonal:
    path:     /saludopersonal/{msg}
    defaults: { _controller: AppBundle:Saludo:saludoPersonal }